version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-local-dev-key
      - ALLOWED_HOSTS=localhost,127.0.0.1
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: thuto_db
      POSTGRES_USER: thuto_user
      POSTGRES_PASSWORD: thuto_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
