apiVersion: apps/v1
kind: Deployment
metadata:
  name: thuto-app
  namespace: thuto
  labels:
    app: thuto-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: thuto-app
  template:
    metadata:
      labels:
        app: thuto-app
    spec:
      containers:
      - name: thuto-app
        image: ghcr.io/tokelomakafane/pipelin-demo:IMAGE_TAG
        ports:
        - containerPort: 8000
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: thuto-secrets
              key: SECRET_KEY
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: thuto-secrets
              key: DEBUG
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: thuto-secrets
              key: ALLOWED_HOSTS
        envFrom:
        - configMapRef:
            name: thuto-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
