apiVersion: apps/v1
kind: Deployment
metadata:
  name: thuto-app
  namespace: thuto
  labels:
    app: thuto-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thuto-app
  template:
    metadata:
      labels:
        app: thuto-app
    spec:
      containers:
      - name: thuto-app
        image: ghcr.io/tokelomakafane/pipelin-demo:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
